/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "ip.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BroadcastMessage, BroadcastMessage, 2)


PB_BIND(DiscoveryResponse, DiscoveryResponse, 2)


PB_BIND(ToReceiver, ToReceiver, AUTO)


PB_BIND(ToTransmitter, ToTransmitter, 2)


PB_BIND(ReceiverInformation, ReceiverInformation, 2)


PB_BIND(ReceiverError, ReceiverError, AUTO)


PB_BIND(AudioData, AudioData, AUTO)



