/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AudioReceiverAnnouncement { 
    uint32_t magic_word; 
    uint64_t mac_address; 
    pb_callback_t device_name; 
    bool currently_streaming; 
} AudioReceiverAnnouncement;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AudioReceiverAnnouncement_init_default   {0, 0, {{NULL}, NULL}, 0}
#define AudioReceiverAnnouncement_init_zero      {0, 0, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AudioReceiverAnnouncement_magic_word_tag 1
#define AudioReceiverAnnouncement_mac_address_tag 2
#define AudioReceiverAnnouncement_device_name_tag 4
#define AudioReceiverAnnouncement_currently_streaming_tag 5

/* Struct field encoding specification for nanopb */
#define AudioReceiverAnnouncement_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   magic_word,        1) \
X(a, STATIC,   REQUIRED, UINT64,   mac_address,       2) \
X(a, CALLBACK, REQUIRED, STRING,   device_name,       4) \
X(a, STATIC,   REQUIRED, BOOL,     currently_streaming,   5)
#define AudioReceiverAnnouncement_CALLBACK pb_default_field_callback
#define AudioReceiverAnnouncement_DEFAULT NULL

extern const pb_msgdesc_t AudioReceiverAnnouncement_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AudioReceiverAnnouncement_fields &AudioReceiverAnnouncement_msg

/* Maximum encoded size of messages (where known) */
/* AudioReceiverAnnouncement_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
